-- DO NOT EDIT THIS FILE DIRECTLY. LOCALIZATION IS HANDLED USING CURSEFORGE LOCALIZATION
Library.Translate.En(
{
	WildGrowthGadget_name = "Wild Growth Gadget",
	WildGrowthGadget_desc = "Wild Growth Gadget",
	WildGrowth = "Wild Growth",
	Orchestra = "Orchestra of the Planes",
	FlaringPower = "Faring Power",
	WildGrowthGadgetConfigDesc = "The Wild Growth Gadget shows timers Of Wild Growth and Cooldowns",
	UnitToTrack = "Unit To Track",
	WhatBuffToTrack = "What Buff to Track",
}
)
